<?php
declare(strict_types=1);

namespace Digitalway\SocialLogin\Model;

use Magento\Customer\Api\AccountManagementInterface;
use Magento\Customer\Api\Data\CustomerInterface;
use Magento\Customer\Model\Session as CustomerSession;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Stdlib\Cookie\CookieMetadataFactory;
use Magento\Framework\Stdlib\CookieManagerInterface;

/**
 * Login like Magento\Customer\Controller\Account\LoginPost: the session is
 * regenerated by setCustomerDataAsLoggedIn(); deleting mage-cache-sessid
 * makes customer-data.js reload all private sections.
 */
class LoginHandler
{
    private const CUSTOMER_DATA_COOKIE = 'mage-cache-sessid';

    public function __construct(
        private readonly CustomerSession $session,
        private readonly AccountManagementInterface $accountManagement,
        private readonly CookieManagerInterface $cookieManager,
        private readonly CookieMetadataFactory $cookieMetadataFactory
    ) {
    }

    /**
     * @throws LocalizedException
     */
    public function login(CustomerInterface $customer): void
    {
        $status = $this->accountManagement->getConfirmationStatus((int) $customer->getId());
        if ($status === AccountManagementInterface::ACCOUNT_CONFIRMATION_REQUIRED) {
            throw new LocalizedException(__(
                'Your account is not confirmed yet: check your email and follow the confirmation link.'
            ));
        }

        $this->session->setCustomerDataAsLoggedIn($customer);

        if ($this->cookieManager->getCookie(self::CUSTOMER_DATA_COOKIE)) {
            $metadata = $this->cookieMetadataFactory->createCookieMetadata();
            $metadata->setPath('/');
            $this->cookieManager->deleteCookie(self::CUSTOMER_DATA_COOKIE, $metadata);
        }
    }
}
